### ISSUE TITLE
decorateIcons implementation mixes sync and async

### ISSUE THREAD

**Issue by kptdobe** [adobe/aem-boilerplate#147]
Current `decorateIcons` [implementation](https://github.com/adobe/helix-project-boilerplate/blob/main/scripts/lib-franklin.js#L130) is misleading: while it works, after a call to `decorateIcons`, the DOM might not yet be up to date because of the async callback in the `forEach`.

**Comment by bstopp** [comment]
I think this is no longer an issue given the change icons are handled.
