### ISSUE TITLE
Add a check of the hash of aem.js as part of the git PR workflow?

### ISSUE THREAD

**Issue by shsteimer** [adobe/aem-boilerplate#272]
Consider this an idea more than concrete proposal

I've run across a number of ACS and partner projects who are modifying aem.js as their default way of changing things, as opposed to doing it in scripts.js. I view modifying aem.js as not necessarily verboten, but to be avoided when possible.

But my thought would be to have the PR workflow check the hash against a known value, and if it doesn't match, print a message indicating to use caution when modifying, etc.

If the project really wants to or needs to, they can update the hash in the pr script and move on, but should at least encourage the right behavior.  thoughts?

**Comment by amol-anand** [comment]
> If the project really wants to or needs to, they can update the hash in the pr script and move on, but should at least encourage the right behavior. thoughts?

It can also be more of a warning that can be overridden similar to PSI check today.
