### ISSUE TITLE
Add codeBasePath reference in header and footer blocks

### ISSUE THREAD

**Issue by asthabh23** [adobe/aem-boilerplate#273]
Reference of `${window.hlx.codeBasePath}` to be added by default in header and footer blocks.
This will be helpful for projects dealing with subpaths for site URL

**Comment by kptdobe** [comment]
Can you please provide a concrete problem you are trying to solve ?

**Comment by rofe** [comment]
Closing for now, see https://github.com/adobe/aem-boilerplate/pull/274#issuecomment-1782542120
