### ISSUE TITLE
Update to Icon SVG Handling created Accessibility regression

### ISSUE THREAD

**Issue by bstopp** [adobe/aem-boilerplate#279]
### Expected Behaviour

Icons should contain some form of `alt` text for the image tag.

### Actual Behaviour

No `alt` text exists, and thus Accessibility issue is raised on PSI check.

#### Steps to Reproduce

Load any demo page. [Here is a PSI check](https://pagespeed.web.dev/analysis/https-main--aem-eds-demo--bstopp-hlx-page/og2eede810?form_factor=mobile) of a page with multiple icon references.

**Comment by alexcarol** [comment]
Do we consider it solved with https://github.com/adobe/aem-lib/pull/26 ?
