### ISSUE TITLE
Remove Lint Rule: no-use-before-define

### ISSUE THREAD

**Issue by synox** [adobe/aem-boilerplate#319]
I want to suggest to remove the `no-use-before-define` rule. https://eslint.org/docs/latest/rules/no-use-before-define

This currently leads defining functions in the following order, from granular to important: 
 - helper functions
 - dom manipulation functions
 - decorator function

e.g. https://github.com/adobe/aem-boilerplate/blob/main/blocks/header/header.js#L93

I would prefer to do the opposite. I would like the decorator function to be on top as the entry point, and non-important helper functions on the bottom. 

The way I understand JS, functions can still be defined in any order, while variables have the be in the right order. 

Let's discuss.

**Comment by kptdobe** [comment]
If we allow that, it will be the mess: sometimes ordered will the respected, sometimes not. With the current rule, you can be sure to find the decorator function at the end.
